name       : i3blocks
version    : 1.4
release    : 1
source     :
    - https://github.com/vivien/i3blocks/releases/download/1.4/i3blocks-1.4.tar.gz : c64720057e22cc7cac5e8fcd58fd37e75be3a7d5a3cb8995841a7f18d30c0536
license    : GPL-3.0
component  : desktop
summary    : A flexible scheduler for your i3bar blocks
description: |
    A flexible scheduler for your i3bar blocks
build      : |
    %make PREFIX=/usr LIBEXECDIR=%libdir%/libexec/
install    : |
    %make_install PREFIX=/usr LIBEXECDIR=%libdir%/libexec/
