name       : i3blocks
version    : '1.5'
release    : 5
source     :
    - https://github.com/vivien/i3blocks/archive/refs/tags/1.5.tar.gz : 41764d771043d0c06c23d75b1e3ca6b2b94279191483d03f10c5e034d6722ebf
homepage   : https://github.com/vivien/i3blocks
license    : GPL-3.0-or-later
component  : desktop.i3
summary    : A feed generator for text based status bars
description: |
    i3blocks executes your command lines and generates a status line from their output. Commands are scheduled at configured time intervals, upon signal reception or on clicks.
rundeps    :
    - acpi
    - sysstat
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install -j1
